const autoprefixer = require('autoprefixer')
const purgecss = require('@fullhuman/postcss-purgecss')

module.exports = {
  plugins: [
    autoprefixer(),
    purgecss({
      content: [
        './layouts/**/*.html',
        './layouts/**/*.svg',
        './content/**/*.md',
      ],
      safelist: [
        'mobile-dropdown-open',
        'is-active',
        'nav-open',
        'has-dropdown-open',
        'has-sub-menu-open',
        'expand',
        'collapse',
        'page-home',
        'page-about',
        'page-contact',
        'page-welding',
        'page-concrete',
        'page-careers',
        'page-thank-you',
        'page-frequently-asked-questions',
        'page-are-we-the-right-builder-for-you',
        'parent-page-home',
        'parent-page-about',
        'parent-page-construction-services',
        'parent-page-portfolio',
        'parent-page-contact',
        'parent-page-resources',
        'parent-page-careers',
        'parent-page-sectors',
        'category-videos',
        'active-button',
        'position-open',
        'list-open',
        'toggle-mobile-dropdown',
        'ul', 
        'ol',
        'table',
        'tr',
        'td',
        'pre',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'btn--active',
        'blog--grid',
        'video-playing',
        'video-paused',
        'slider-playing',
        'slider-paused',
        'swiper-slide-thumb-active',
        'submenu-about',
        'wistia_click_to_play',
        'mc_embed_signup',
      ],
    }),
  ],
}